### ISSUE TITLE
Example user persona - April 6

### ISSUE THREAD

**Issue by mfreema5** [spring15wad/rollingread#2]
From the UX Book, starting on p. 264

> A persona is not an actual user, but a pretend user or a “hypothetical archetype” (Cooper, 2004). A persona represents a specific person in a specific work role and sub-role, with specific user class characteristics. Built up from contextual data, a persona is a story and description of a specific individual who has a name, a life, and a personality.

…

> A specific persona makes clear what functionality or features must be included and what can be omitted. It is much easier to argue whether a person represented by a specific persona would like or use a given design feature.

…

> One of the strengths of personas is that they deflect this tendency of designers to design for themselves. Because of their very real and specific characteristics, personas hold designers’ feet to the fire and help them think about designs for people other than themselves. Personas help designers look outward instead of inward. Personas help designers ask “How would Rachel use this feature?”, forcing them to look at the design from Rachel’s perspective. The description of a persona needs to make it so well defined as a real and living being that it is impossible for a designer or programmer to substitute themselves or their own characteristics when creating the design.

**Comment by mfreema5** [comment]
Just a possible starting point. Y'all can go a completely different direction if you want.  But maybe a seed of an idea will help get things going?

----
## Nicole Farnsworth

![nicole-farnsworth](https://cloud.githubusercontent.com/assets/5863302/7007674/9df900b8-dc51-11e4-8e2b-54ee4c4ad54c.jpg)

* What's she studying?
* What's her living arrangements (roommates, etc.)?
* Does she have a job off-campus?  On campus?
* What sort of devices does she uses to access on-line resources?
* Is she usually ahead of schedule, behind schedule, or right-on-schedule?
* Are her friends also students?  A mix of students and non-students?
* Does she enjoy reading?  How does she feel about reading textbooks?

She sometimes envisions a super-hero version of herself, GGIRL.
![super-nicole](https://cloud.githubusercontent.com/assets/5863302/7007716/d999c6d4-dc51-11e4-9782-ca8de0d4a9ef.jpeg)

**Comment by jhignight** [comment]
I like it. I'll provide some sample info to get things rolling (see what I did there?):
1. Nicole is studying Political Science.
2. Nicole lives in a suite-style dorm with 2 other suite-mates (another girl studying Architectural Engineering and a gay male studying Computer Science).
3. Nicole has a work-study job in the campus library. She works 12 hours per week.
4. Nicole uses her iPhone as well as iPad. She also has a Compaq laptop she keeps at home.
5. Nicole tends to be right-on schedule, but falls a bit behind at times.
6. Nicole's friends are primarily other students on campus, in her program.
7. Nicole enjoys reading fanfiction (particularly relating to Harry Potter), and she typically enjoys reading textbooks regarding Political Science, although sometimes she puts off readings because they can be a bit dry.

**Comment by mfreema5** [comment]
Nice.

I think that's good enough to call this issue closed, and move on to usage scenarios and [storyboarding how Nicole uses RollingRead](https://github.com/spring15wad/rollingread/issues/3).
